default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= Figaro.env.postgres_user || "postgres" %>
  password: <%= Figaro.env.postgres_pass || "" %>
  pool: <%= ENV.fetch("DATABASE_POOL", 5) %>
  timeout: 5000

development:
  <<: *default
  database: project_name_development

test:
  <<: *default
  database: project_name_test

production:
  <<: *default
  database: project_name_production
